name: Index Library
on: [push]
jobs:
  Index-Library:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      #- run: sudo apt-get update && sudo apt-get install -y libreoffice libreoffice-java-common
      #- run: soffice --headless --convert-to pdf ./Example.odt
      #- name: Test Commit
      #  uses: EndBug/add-and-commit@v9
      #  with:
      #    add: "Example.pdf"
